config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flights, only: [:index]
  get "autocomplete" , to: 'flights#autocomplete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight
  include ActiveModel::Model

  attr_accessor :departure_airport,
                :departure_datetime,
                :departure_timezone,
                :arrival_airport,
                :arrival_datetime ,
                :arrival_timezone,
                :flight_number,
                :marketing_airline,
                :step

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

#Needed for metatags
  def default_url_options
  { host: ENV['HOST'] || 'localhost:3000' }
  end

end

app/controllers/flights_controller.rb
require 'date'    # If not already required. If in Rails then you don't need this line).

class FlightsController < ApplicationController
  token = SacsRuby.client.fetch_token
  token.access_token
  token.expires_on

  def index

    @trip_periode = params[:periode].downcase.capitalize

    # User Params
    params[:periode] = params[:periode].downcase.capitalize

    start_period = date_params(params[:periode])[1]
    end_period = date_params(params[:periode])[0]
    lengthofstay = params[:duration].join

    @periode = ["Choisissez votre période","Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"]
    @passagers_number = ["0","1","2","3","4","5"]


    search_params = {
      origin: params[:departure].match(/\((.*)\)/)[1],
      destination: params[:destination].match(/\((.*)\)/)[1],
      lengthofstay: params[:duration].join,
      end_period: end_period.to_date,
      departuredate: start_period,
      returndate: (start_period.to_date + lengthofstay.to_i).to_s

    }

    @trips_results = ::GetFlightsService.new(search_params).call
  end

  def autocomplete
   @mode = params[:mode]
   @list = ::AutoCompleteService.new(params[:query]).call
   respond_to do |format|
     format.js
   end
 end




private


  def sort_by_duration(results)
  end

  def date_params(date)

    last_day_hash = {
      "Janvier 2017" => "31",
      "Février 2017" => "28",
      "Mars 2017" => "31",
      "Avril 2017" => "30",
      "Mai 2017" => "31",
      "Juin 2017" => "30",
      "Juillet 2017" => "31",
      "Aout 2017" => "31",
      "Septembre 2017" => "30",
      "Octobre 2017" => "31",
      "Novembre 2017" => "30",
      "Decembre 2017" => "31",

    };

    month_hash = {
      "Janvier 2017" => "01",
      "Février 2017" => "02",
      "Mars 2017" => "03",
      "Avril 2017" => "04",
      "Mai 2017" => "05",
      "Juin 2017" => "06",
      "Juillet 2017" => "07",
      "Aout 2017" => "08",
      "Septembre 2017" => "09",
      "Octobre 2017" => "10",
      "Novembre 2017" => "11",
      "Decembre 2017" => "12",

    }

    results = ["2017" + "-" + month_hash[date] +"-" + last_day_hash[date],
    "2017" + "-" + month_hash[date] + "-01"]
  end

  # Fake flights for testing
  # def generate_sample_trips
  #   trips = []
  #   10.times do
  #     start_flight = Flight.new(
  #       start_place:["CDG","DPS","JFK","AMS","LGE"].sample,
  #       end_place:["CDG","DPS","JFK","AMS","LGE"].sample,
  #       start_date: DateTime.now + rand(1..10).days,
  #       end_date:DateTime.now + rand(11..15).days,
  #       company: ["Air France","Luftansa", "Vueling"].sample,
  #       flight_duration: [ "6H30" , "1H30", "12H40","7H00" ].sample
  #     )

  #     return_flight = Flight.new(
  #       start_place:["CDG","DPS","JFK","AMS","LGE"].sample,
  #       end_place:["CDG","DPS","JFK","AMS","LGE"].sample,
  #       start_date: DateTime.now + rand(16..20).days,
  #       end_date:DateTime.now + rand(21..30).days,
  #       company: ["Air France","Luftansa", "Vueling"].sample,
  #       flight_duration: [ "6H30" , "1H30", "12H40","7H00" ].sample
  #     )

  #     trip_price = [350, 600, 700, 1300].sample
  #     currency = ["$","¥","€"].sample
  #     global_start_trip_duration = rand(3..50)
  #     global_return_trip_duration = rand(3..50)

  #     trip = {
  #       start_flight: start_flight,
  #       return_flight: return_flight,
  #       trip_price: trip_price,
  #       currency: currency,
  #       global_start_trip_duration: global_start_trip_duration,
  #       global_return_trip_duration: global_return_trip_duration
  #     }
  #     trips << trip
  #   end
  #   return trips
  # end

  # def sort_by_duration(results)
  # end

  # def date_params(date)

  #   last_day_hash = {
  #     "Janvier 2017" => "31",
  #     "Février 2017" => "28",
  #     "Mars 2017" => "31",
  #     "Avril 2017" => "30",
  #     "Mai 2017" => "31",
  #     "Juin 2017" => "30",
  #     "Juillet 2017" => "31",
  #     "Aout 2017" => "31",
  #     "Septembre" => "30",
  #     "Octobre" => "31",
  #     "Novembre" => "30",
  #     "Decembre 2016" => "31",

  #   };



  #   month_hash = {
  #     "Janvier 2017" => "01",
  #     "Février 2017" => "02",
  #     "Mars 2017" => "03",
  #     "Avril 2017" => "04",
  #     "Mai 2017" => "05",
  #     "Juin" => "06",
  #     "Juillet" => "07",
  #     "Aout" => "08",
  #     "Septembre" => "09",
  #     "Octobre" => "10",
  #     "Novembre" => "11",
  #     "Decembre" => "12",

  #   }

    # results = ["2017" + "-" + month_hash[date] +"-" + last_day_hash[date],
    # "2017" + "-" + month_hash[date] + "-01"]
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @periode = month_ordered
    @passagers_number = ["0","1","2","3","4","5"]

  end

  def month_ordered
    date = Time.now
    actual_month = date.month - 1
    actual_year = date.year
    last_months = []
    first_months = []
    months = ["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"]
    months.map.with_index do |x, i|
      if i < actual_month
        x = x + " " + "#{actual_year + 1}"
        last_months << x
      else
        x = x + " " + "#{actual_year}"
        first_months << x
      end
    end
    results = first_months + last_months
    results = results.first(6)
    return results

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image']
  end
end

app/views/flights/_airports_results.html.erb
<div class="search__title">
 Choisissez votre ville
</div>
<div class="collection">
   <% airports_list.each do |airport| %>
     <div class="collection-item city_<%= mode %>" data-city='<%= airport %>'> <i class="fa fa-map-marker" aria-hidden="true"></i> <%= airport %> </div>
   <%end%>
</div>

app/views/flights/_result_details.html.erb
<h3 class="title_flight">Vol aller</h3>
<div class="collection flight_card">
  <div class="collection-item one_trip_table">
    <div class="row trip_table_head">
      <div class="col m4 text-center">
        <div class="time"><i class="fa fa-calendar" aria-hidden="true"></i></div>
      </div>
      <div class="col m4">
        <div class="place"><i class="fa fa-globe" aria-hidden="true"></i></div>
      </div>
      <div class="col m4">
        <div class="company"><i class="fa fa-ticket" aria-hidden="true"></i></div>
      </div>
    </div>
    <div class="row">
      <div class="col m4 s6">
        <div class="time">
          <div class="take_off_time">
            <p class="date"><%=l(result_details[:depart_date].to_time, format: "%a, %d %b").capitalize %></p>
            <p class="date"><%=result_details[:depart_date].to_time.strftime("%H:%M") %></p>
          </div>
        </div>
      </div>
      <div class="col m4 s6">
        <div class="place">
          <p class="take_off_place"><%=result_details[:depart_OriginStation]%></p>
        </div>
      </div>
      <div class="col m4 s12">
        <div class="company">
          <img src="<%= "http://0.omg.io/wego/image/upload/c_fit,w_200,h_70/flights/airlines_rectangular/" + result_details[:depart_company] + ".png"%>" alt="company" style="max-width:100%;  padding-top: 15px;">
        </div>
      </div>
      <div class="col m4 s6">
        <div class="time">
          <div class= "landing_time">
            <p class="date"><%= l(result_details[:depart_date_arrival].to_time, format: "%a, %d %b").capitalize %></p>
            <p class="date"><%=result_details[:depart_date_arrival].to_time.strftime("%H:%M") %></p>
          </div>
        </div>
      </div>
      <div class="col m4 s6">
        <div class="place">
          <p class="landing_place"><%=result_details[:depart_DestinationStation]%></p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col m12">
        <div class="stopover_nb">
          <p style="text-align: right">Nombre d'escales: <%= result_details[:depart_segments_number]%> <span style="color:#0072BB"></span></p>
        </div>
      </div>
    </div>
  </div>
</div>

<h3 class="title_flight">Vol retour</h3>
<div class=" collection flight_card">
  <div class="collection-item one_trip_table">
    <div class="row trip_table_head">
      <div class="col m4">
        <div class="time"><i class="fa fa-calendar" aria-hidden="true"></i></div>
      </div>
      <div class="col m4">
        <div class="place"><i class="fa fa-globe" aria-hidden="true"></i></div>
      </div>
      <div class="col m4">
        <div class="company"><i class="fa fa-ticket" aria-hidden="true"></i></div>
      </div>
    </div>
    <div class="row">
      <div class="col m4">
        <div class="time">
          <div class="take_off_time">
            <p class="date"><%= l(result_details[:return_date].to_time, format: "%a, %d %b").capitalize %></p>
            <p class="date"><%=result_details[:return_date].to_time.strftime("%H:%M") %></p>
          </div>
        </div>
      </div>
      <div class="col m4">
        <div class="place">
          <p class="take_off_place"><%=result_details[:return_OriginStation]%></p>
        </div>
      </div>
      <div class="col m4">
        <div class="company">
          <img src="<%= "http://0.omg.io/wego/image/upload/c_fit,w_200,h_70/flights/airlines_rectangular/" + result_details[:return_company] + ".png"%>" alt="company" style="max-width:100%; padding-top: 15px;">
        </div>
      </div>
      <div class="col m4">
        <div class="time">
          <div class="landing_time">
            <p class="date"><%= l(result_details[:return_date_arrival].to_time, format: "%a, %d %b").capitalize %></p>
            <p class="date"><%=result_details[:return_date_arrival].to_time.strftime("%H:%M") %></p>
          </div>
        </div>
      </div>
      <div class="col m4">
        <div class="place">
          <p class="landing_place"><%=result_details[:return_DestinationStation]%></p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col m12">
        <div class="stopover_nb">
          <p style="text-align: right">Nombre d'escales: <%= result_details[:return_segments_number]%> <span style="color:#0072BB"></span></p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="bouton_voir">
  <%= link_to "+ d'infos", result_details[:deep_link_url], target: "blank", class: "btn-large waves-effect waves-light" %>
</div>

app/views/flights/autocomplete.js.erb
<% if @mode == "departure" %>
  $(".arrow_3_target").html("<%= j render 'airports_results', airports_list: @list, mode: @mode %>");
<%else%>
  $(".arrow_4_target").html("<%= j render 'airports_results', airports_list: @list, mode: @mode %>");
<% end %>

app/views/flights/index.html.erb
<div class="results_wrapper">
  <div class="container">
    <div class="row">
      <div class="col s12">
        <div class="title_div">
          <div class="logo_title">
            <h1><%=link_to "Mac Flight", root_path, :style=>'color: white;' %></h1>
          </div>
        </div>
        <div class="col s6">
          <div class="results_lists result-list">
            <div class="presentation_title-result">
              <h5><%= @trip_periode%></h5>
            </div>
            <div class="scroll_div" style="overflow: scroll; height: 660px;">
              <% @trips_results.each_with_index do |trip, index|%>
                <div class="card-left " data-trip_index="<%= index %>">
                  <div class="collection-item background-date">
                    <div class="datecontainer">
                      <div class="depart-date"> <%= l(trip[:depart_date].to_date, format: '%A %e').capitalize %> </div>
                      <div><i class="fa fa-arrows-h fa-2x" aria-hidden="true"></i></div>
                      <div class="retour-date"> <%= l(trip[:return_date].to_date, format: '%A %e').capitalize %> </div>
                    </div>
                  </div>
                  <div class="slider-date">
                    <div >
                      <div class="date_range_graph_field">
                        <div class="date_range_graph">
                          <div class="date_representation_sliders" data-departure_date_day="<%= trip[:depart_date].to_date.strftime('%e').to_i %>" data-departure_date_month="<%= trip[:depart_date].to_date.strftime('%m') %>" data-arrival_date_day="<%= trip[:return_date].to_date.strftime('%e').to_i %>">
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="flex-container-result">
                    <p style="color:grey">Temps de voyage:</p>
                    <div class="time_flight">
                      <div class="start_flight_duration">
                        <div class="container-flex-icone">
                          <div>
                            <i class="fa fa-plane fa-depart-plane" aria-hidden="true"></i>Aller:
                          </div>
                          <%= trip[:depart_trip_duration]%>
                        </div>
                      </div>
                      <div class="return_flight_duration">
                        <div class="container-flex-icone">
                          <div>
                            <i class="fa fa-plane fa-return-plane" aria-hidden="true"></i>Retour:
                          </div>
                          <%= trip[:return_trip_duration]%>
                        </div>
                      </div>
                    </div>
                    <div class="flight_price">
                      <p><%=trip[:price]%>€</p>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col s6">
          <div class="flight_details_container">
            <div class="presentation_title-result">
              <h5>Détails du vol</h5>
            </div>
            <div id="results_details_container">
              <%= render 'result_details', result_details: @trips_results[0] %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    $(document).ready(function(){
      // Slider initialization
      $('.date_representation_sliders').each(function(){
        var slider = noUiSlider.create(this, {
          start: [$(this).data('departure_date_day'), $(this).data('arrival_date_day')],
          tooltips: true,
          connect: true,
          step: 1,
          range: {
            'min': 1,
            'max': 31,
          },
          format: {
            to: function ( value ) {
              return value + '';
            },
            from: function ( value ) {
              return value.replace('.00', $(this).data('departure_date_month'));
            }
          },
          disabled: true,
        });
        this.setAttribute('disabled', true);
      });

      $('.background-date').first().addClass('select');

      // Flight results
      window.trips_results_details = [];
      <% @trips_results.each_with_index do |result_details, index| %>
        var result_details = "<%= j render 'result_details', result_details: result_details %>";
        window.trips_results_details[<%= index %>] = result_details;
      <% end %>

      // Register click on card result
      $('.card-left').click(function(){
        $('.background-date').removeClass('select');
        $(this).find(".background-date").addClass('select');
        // Detect the index
        var index = $(this).data('trip_index');
        var result_details_div = window.trips_results_details[index];

        $('#results_details_container').html(result_details_div);
      });

    });
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%=favicon_link_tag("logo.png")%>
        <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!-- This is the part to get meta tags -->
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= image_url(meta_image) %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META['twitter_account'] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META['twitter_account'] %>">
    <meta name="twitter:image:src" content="<%= image_url(meta_image) %>">

    <!-- Google+ Schema.org markup -->
    <meta itemprop="name" content="<%= meta_title %>">
    <meta itemprop="description" content="<%= meta_description %>">
    <meta itemprop="image" content="<%= image_url(meta_image) %>">


  </head>
  <body>

    <%= yield %>

    <%= javascript_include_tag 'application' %>


    <%= yield(:after_js) %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col s12">
        <div class="title_div">
          <div class="logo_title">
            <h1>Mac Flight</h1>
          </div>
        </div>
        <div class="col s6">
          <div class="search_card_left">
        <!-- définir la route exact et le type de méthode get/post -->
            <%= form_tag(flights_path, method: :get) do %>
              <div class="search__title">
                Quel est votre trajet ?
              </div>
              <div class="input-field line_1 ">
                <%= number_field(:duration, nil, in: 1..30, step: 1, placeholder: "Durée du séjour en jours", class: "validate field_1") %>
                <div class="arrow-search arrow_1 hidden"></div>
              </div>
              <div class="input-field line_2">
                <%= text_field_tag(:periode, nil, placeholder:"Choisissez votre période", class: "validate") %>
                <div class="arrow-search arrow_2 hidden"></div>
              </div>

                <div class="input-field line_3" id="search">
                  <%= text_field_tag(:departure, nil, placeholder:"Départ", class: "validate") %>
                  <div class="arrow-search arrow_3 hidden"></div>
                </div>
              <div class="input-field line_4" id="search_destination">
                <%= text_field_tag(:destination, nil, placeholder:"Destination", class: "validate") %>
                <div class="arrow-search arrow_4 hidden"></div>
              </div>
              <div>
                <p>Nombre de passagers</p>
              </div>
              <div class="passagers_selection">
                <div class="input-field passagers_child">
                  <p>Enfant(s)</p>
                  <%= select_tag(:passagers_child, options_for_select(@passagers_number), class: "browser-default") %>
                </div>
                <div class="input-field passagers_young">
                  <p>Jeune(s)</p>
                  <%= select_tag(:passagers_young, options_for_select(@passagers_number), class: "browser-default") %>
                </div>
                <div class="input-field passagers_adult">
                  <p>Adulte(s)</p>
                  <%= select_tag(:passagers_adult, options_for_select(@passagers_number), class: "browser-default") %>
                </div>

              </div>
              <div class="input-field line_5">
                <%= submit_tag("Rechercher", class: "btn waves-effect waves-light search_button") %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="col s6">
          <div class="card_presentation">
            <div class="arrow_0_target">
              <div class="presentation_title">
                <div class="presentation_title_text">
                  Les petits <i class="fa fa-plus-circle" aria-hidden="true"></i> de Macflight
                </div>
              </div>
              <div class="presentation_content">
                <ul>
                  <li><div class="circle_icon_1">Soyez flexible sur la periode <br><span>Vous ne savez pas trop quand partir.</span></div></li>
                  <li><div class="circle_icon_2">Ne perdez plus un jour de vacances <br><span>Vous avez 10 jours ni plus ni moins.</span></div></li>
                  <li><div class="circle_icon_3"></i>Gagnez sur le prix et le temps<br><span>Vous pouvez choisir le meilleur temps de vol au meilleur prix.</span></div></li>
                </ul>
              </div>
              <div class="presentation_footer">
                <div class="presentation_footer_description">
                  Design by MOI
                </div>
              </div>
            </div>
          </div>
          <div class="search_card_right hidden">
            <div class="arrow_1_target search__title hidden">
              Sélectionnez votre nombre de jours
            </div>
            <div class="arrow_1_target hidden collection">
              <div class="collection-item" data-nb_days="2">2 jours</div>
              <div class="collection-item" data-nb_days="3">3 jours</div>
              <div class="collection-item" data-nb_days="5">5 jours</div>
              <div class="collection-item" data-nb_days="7">7 jours</div>
              <div class="collection-item" data-nb_days="10">10 jours</div>
              <div class="collection-item" data-nb_days="14">14 jours</div>
            </div>
            <div class="arrow_2_target hidden">
              <div class="search__title">Séléctionnez votre mois</div>
              <% @periode.each do |month| %>
                <div class="div_month col s6" data-month="<%=month%>" >
                  <div class="card_month">
                    <%= month %>
                  </div>
                </div>
              <% end %>
            </div>
            <div class="arrow_3_target hidden">
              <div class="search__title">
               Choisissez votre ville
              </div>
            </div>
            <div class="arrow_4_target hidden">
              <div class="search__title">
               Choisissez votre ville
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="waiting_message hidden">
    <div class="waiting_message_description">Attachez vos ceintures !</div>
  </div>
</div>

<%= render "cloud", color: "blue" %>

<% content_for(:after_js) do %>
  <script>
    $(document).ready(function(){
      $( ".collection-item" ).click(function() {
        $( ".collection-item" ).removeClass('active');
        $(this).addClass('active');
        var nb_days = $(this).data("nb_days");
        console.log(nb_days)
        $('#duration_').val(nb_days);
      });

      $( ".div_month" ).click(function() {
        $( ".div_month" ).removeClass('active');
        $(this).addClass('active');
        var month = $(this).data("month");
        console.log(month)
        $('#periode').val(month);
      });

//add_city_to_form

       $(".arrow_3_target").on('click','.city_departure', function(){
        $( ".city_departure" ).removeClass('active');
        $(this).addClass('active');
        var city = $(this).data("city");
        $('#departure').val(city);
      });

      $(".arrow_4_target").on('click','.city_destination', function(){
        $( ".city_destination" ).removeClass('active');
        $(this).addClass('active');
        var city = $(this).data("city");
        $('#destination').val(city);
      });


      $('#departure').keypress(function(e){
       var letter = e.target.value;
       var url = "<%= autocomplete_path %>" + ".js?mode=departure"
         $.ajax({
           url: url,
           data: {
             query: letter
           },
           dataType: "script",
           sucess: function(data){
             console.log(data)
           }
         });
      });

      $('#destination').keypress(function(e){
       var letter = e.target.value;
       var url = "<%= autocomplete_path %>" + ".js?mode=destination"
         $.ajax({
           url: url,
           data: {
             query: letter
           },
           dataType: "script",
           sucess: function(data){
             console.log(data)
           }
         });
      });

    })

    $('#departure').keypress(function(e){
     var letter = e.target.value;
     var url = "<%= autocomplete_path %>" + ".js"
     $.ajax({
       url: url,
       data: {
         query: letter
       },
       dataType: "script",
       sucess: function(data){
         console.log(data)
       }
     })
   });
  </script>

<% end %>